config/routes.rb
Rails.application.routes.draw do

  resources :statistics
  resources :shortcut_texts
  resources :tips
  resources :tasks
  resources :generated_feedbacks
  resources :maths_grades
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
post 'signup' => 'devise/registrations#create', :as => :custom_user_registration

devise_scope :user do
  root to: "devise/sessions#new"
end

 resources :teacher

 resources :student
resources :english_grades


 resources :choose_subjects
 resources :choose_feedback_generator

 resources :edit_auto_gens
end

app/models/student.rb
class Student < User
    has_many :grades
    has_many :maths_grades
    has_many :english_grades
    has_many :generated_feedback
end

app/controllers/student_controller.rb
class StudentController < ApplicationController
before_filter :authenticate_user!
before_filter do
    redirect_to new_user_session_path unless current_teacher || params[:id] == nil
    end


    def current_teacher
        current_user.type == 'Teacher'
    end




    def index
        @teacher = Teacher.where('email' => current_user.teacher_email)
        #really hacky but so that i can still do .each and with this select a single teacher
        @teacher_other = Teacher.where('email' => current_user.teacher_email).first
        @all_english_grades = current_user.english_grades.all

        @all_maths_grades = current_user.maths_grades.all
        @latest_two_english_grade = EnglishGrade.where(:student_id => current_user.id).where('grade_date <= ?', Time.zone.now).last(2).reverse
        @latest_two_maths_grade = MathsGrade.where(:student_id => current_user.id).where('grade_date <= ?', Time.zone.now ).last(2).reverse

        #English
        #Generated feedback - writing
        @generated_feedback_writing_not_started = GeneratedFeedback.where({teacher_id: @teacher_other.id, subject: 'English', subcategory: 'Writing', performance_grade: 'Not-started'}).last
        @generated_feedback_writing_working_towards = GeneratedFeedback.where({teacher_id: @teacher_other.id, subject: 'English', subcategory: 'Writing', performance_grade: 'Working-towards'}).last
        @generated_feedback_writing_working_at = GeneratedFeedback.where({teacher_id: @teacher_other.id, subject: 'English', subcategory: 'Writing', performance_grade: 'Working-at'}).last
        @generated_feedback_writing_greater_depth = GeneratedFeedback.where({teacher_id: @teacher_other.id, subject: 'English', subcategory: 'Writing', performance_grade: 'Greater-depth'}).last
        #Generated feedback - spelling
        @generated_feedback_spelling_not_started = GeneratedFeedback.where({teacher_id: @teacher_other.id, subject: 'English', subcategory: 'Spelling', performance_grade: 'Not-started'}).last
        @generated_feedback_spelling_working_towards = GeneratedFeedback.where({teacher_id: @teacher_other.id, subject: 'English', subcategory: 'Spelling', performance_grade: 'Working-towards'}).last
        @generated_feedback_spelling_working_at = GeneratedFeedback.where({teacher_id: @teacher_other.id, subject: 'English', subcategory: 'Spelling', performance_grade: 'Working-at'}).last
        @generated_feedback_spelling_greater_depth = GeneratedFeedback.where({teacher_id: @teacher_other.id, subject: 'English', subcategory: 'Spelling', performance_grade: 'Greater-depth'}).last
        #Generated feedback - reading
        @generated_feedback_reading_not_started = GeneratedFeedback.where({teacher_id: @teacher_other.id, subject: 'English', subcategory: 'Reading', performance_grade: 'Not-started'}).last
        @generated_feedback_reading_working_towards = GeneratedFeedback.where({teacher_id: @teacher_other.id, subject: 'English', subcategory: 'Reading', performance_grade: 'Working-towards'}).last
        @generated_feedback_reading_working_at = GeneratedFeedback.where({teacher_id: @teacher_other.id, subject: 'English', subcategory: 'Reading', performance_grade: 'Working-at'}).last
        @generated_feedback_reading_greater_depth = GeneratedFeedback.where({teacher_id: @teacher_other.id, subject: 'English', subcategory: 'Reading', performance_grade: 'Greater-depth'}).last

        #Maths
        #Generated feedback - number
        @generated_feedback_number_not_started = GeneratedFeedback.where({teacher_id: @teacher_other.id, subject: 'Maths', subcategory: 'Number', performance_grade: 'Not-started'}).last
        @generated_feedback_number_working_towards = GeneratedFeedback.where({teacher_id: @teacher_other.id, subject: 'Maths', subcategory: 'Number', performance_grade: 'Working-towards'}).last
        @generated_feedback_number_working_at = GeneratedFeedback.where({teacher_id: @teacher_other.id, subject: 'Maths', subcategory: 'Number', performance_grade: 'Working-at'}).last
        @generated_feedback_number_greater_depth = GeneratedFeedback.where({teacher_id: @teacher_other.id, subject: 'Maths', subcategory: 'Number', performance_grade: 'Greater-depth'}).last

        #Generated feedback - measurement
        @generated_feedback_measurement_not_started = GeneratedFeedback.where({teacher_id: @teacher_other.id, subject: 'Maths', subcategory: 'Measurement', performance_grade: 'Not-started'}).last
        @generated_feedback_measurement_working_towards = GeneratedFeedback.where({teacher_id: @teacher_other.id, subject: 'Maths', subcategory: 'Measurement', performance_grade: 'Working-towards'}).last
        @generated_feedback_measurement_working_at = GeneratedFeedback.where({teacher_id: @teacher_other.id, subject: 'Maths', subcategory: 'Measurement', performance_grade: 'Working-at'}).last
        @generated_feedback_measurement_greater_depth = GeneratedFeedback.where({teacher_id: @teacher_other.id, subject: 'Maths', subcategory: 'Measurement', performance_grade: 'Greater-depth'}).last

        #Generated feedback - geometry
        @generated_feedback_geometry_not_started = GeneratedFeedback.where({teacher_id: @teacher_other.id, subject: 'Maths', subcategory: 'Geometry', performance_grade: 'Not-started'}).last
        @generated_feedback_geometry_working_towards = GeneratedFeedback.where({teacher_id: @teacher_other.id, subject: 'Maths', subcategory: 'Geometry', performance_grade: 'Working-towards'}).last
        @generated_feedback_geometry_working_at = GeneratedFeedback.where({teacher_id: @teacher_other.id, subject: 'Maths', subcategory: 'Geometry', performance_grade: 'Working-at'}).last
        @generated_feedback_geometry_greater_depth = GeneratedFeedback.where({teacher_id: @teacher_other.id, subject: 'Maths', subcategory: 'Geometry', performance_grade: 'Greater-depth'}).last


        #Tasks
        @all_tasks = Task.where({teacher_id: @teacher_other.id}).all


        #Tips

        @tip = Tip.where(:audience => 'student').order('RANDOM()').first
    end

#using the incorrect params jst to make it work
    def show
        @student = Student.find_by_id(params[:id])
        @all_maths_grades = @student.maths_grades.all
    @all_english_grades = @student.english_grades.all


      @teacher_other = current_user

        @latest_two_english_grade = EnglishGrade.where(:student_id => @student.id).last(2).reverse
        @latest_two_maths_grade = MathsGrade.where(:student_id => @student.id).last(2).reverse

        #English
        #Generated feedback - writing
        @generated_feedback_writing_not_started = GeneratedFeedback.where({teacher_id: @teacher_other.id, subject: 'English', subcategory: 'Writing', performance_grade: 'Not-started'}).last
        @generated_feedback_writing_working_towards = GeneratedFeedback.where({teacher_id: @teacher_other.id, subject: 'English', subcategory: 'Writing', performance_grade: 'Working-towards'}).last
        @generated_feedback_writing_working_at = GeneratedFeedback.where({teacher_id: @teacher_other.id, subject: 'English', subcategory: 'Writing', performance_grade: 'Working-at'}).last
        @generated_feedback_writing_greater_depth = GeneratedFeedback.where({teacher_id: @teacher_other.id, subject: 'English', subcategory: 'Writing', performance_grade: 'Greater-depth'}).last
        #Generated feedback - spelling
        @generated_feedback_spelling_not_started = GeneratedFeedback.where({teacher_id: @teacher_other.id, subject: 'English', subcategory: 'Spelling', performance_grade: 'Not-started'}).last
        @generated_feedback_spelling_working_towards = GeneratedFeedback.where({teacher_id: @teacher_other.id, subject: 'English', subcategory: 'Spelling', performance_grade: 'Working-towards'}).last
        @generated_feedback_spelling_working_at = GeneratedFeedback.where({teacher_id: @teacher_other.id, subject: 'English', subcategory: 'Spelling', performance_grade: 'Working-at'}).last
        @generated_feedback_spelling_greater_depth = GeneratedFeedback.where({teacher_id: @teacher_other.id, subject: 'English', subcategory: 'Spelling', performance_grade: 'Greater-depth'}).last
        #Generated feedback - reading
        @generated_feedback_reading_not_started = GeneratedFeedback.where({teacher_id: @teacher_other.id, subject: 'English', subcategory: 'Reading', performance_grade: 'Not-started'}).last
        @generated_feedback_reading_working_towards = GeneratedFeedback.where({teacher_id: @teacher_other.id, subject: 'English', subcategory: 'Reading', performance_grade: 'Working-towards'}).last
        @generated_feedback_reading_working_at = GeneratedFeedback.where({teacher_id: @teacher_other.id, subject: 'English', subcategory: 'Reading', performance_grade: 'Working-at'}).last
        @generated_feedback_reading_greater_depth = GeneratedFeedback.where({teacher_id: @teacher_other.id, subject: 'English', subcategory: 'Reading', performance_grade: 'Greater-depth'}).last

        #Maths
        #Generated feedback - number
        @generated_feedback_number_not_started = GeneratedFeedback.where({teacher_id: @teacher_other.id, subject: 'Maths', subcategory: 'Number', performance_grade: 'Not-started'}).last
        @generated_feedback_number_working_towards = GeneratedFeedback.where({teacher_id: @teacher_other.id, subject: 'Maths', subcategory: 'Number', performance_grade: 'Working-towards'}).last
        @generated_feedback_number_working_at = GeneratedFeedback.where({teacher_id: @teacher_other.id, subject: 'Maths', subcategory: 'Number', performance_grade: 'Working-at'}).last
        @generated_feedback_number_greater_depth = GeneratedFeedback.where({teacher_id: @teacher_other.id, subject: 'Maths', subcategory: 'Number', performance_grade: 'Greater-depth'}).last

        #Generated feedback - measurement
        @generated_feedback_measurement_not_started = GeneratedFeedback.where({teacher_id: @teacher_other.id, subject: 'Maths', subcategory: 'Measurement', performance_grade: 'Not-started'}).last

app/helpers/student_helper.rb
module StudentHelper
end

app/views/student/all_english_grades.html.erb
<head>
<link href='https://fonts.googleapis.com/css?family=Open+Sans&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
</head>

<% if user_signed_in? %>
<ul id="navbar">
    <li class="active"><%=link_to('Home', root_path)%></li>
    <li><%= link_to('Settings', edit_user_registration_path)  %></li>
    <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
</ul>
<% else %>
<ul id="navbar">
    <li><%= link_to('Home', root_path)  %></li>
    <li><%= link_to('Login', new_user_session_path)  %></li>
</ul>
<% end %>

app/views/student/index.html.erb
<head>
<link href='https://fonts.googleapis.com/css?family=Open+Sans&subset=latin,latin-ext' rel='stylesheet' type='text/css'>

<style>
body {
   background: url(https://photos-6.dropbox.com/t/2/AABO-zyEY2tOjMWLE104A8VUTNP-OKx3304nOyxkkd4SUA/12/232060938/jpeg/32x32/1/_/1/2/2015-09-Life-of-Pix-free-stock-photos-road-desert-bus-fresonneveld.jpg/EMGkycQBGNe4AiAHKAc/1FCxtUYuYCMA_UVWkGTRrrdc-EXOXR8d4yf0iBn_sZg?dl=0&size=2048x1536&size_mode=3);

}
h2 {
    color: white;
}
li {color: steelblue;
}
.taskcard {
    width:500px;
    height:50px;
    background-color:white;
    z-index:0;
    opacity:0.5;
    position: relative;
    right: -20px;
}

.teacher_tips1 {
    width:660px;
    height:100px;
    background-color:white;
    z-index:0;
    opacity:0.5;
    position:relative;
    padding-top: -20px;
    left: 10px;
}

</style>

</head>

<% if user_signed_in? %>
<ul id="navbar">
    <li class="active"><%=link_to("#{current_user.first_name} #{current_user.last_name} (Student)", root_path)%></li>
    <li><%= link_to('Settings', edit_user_registration_path)  %></li>
    <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
</ul>
<% else %>
<ul id="navbar">
    <li><%= link_to('Home', root_path)  %></li>
    <li><%= link_to('Login', new_user_session_path)  %></li>
</ul>
<% end %>





<div class = "row">
    <div class = "col-md-6">
        <% unless @all_tasks.blank? %>
            <h2>Task</h2>
        <% end %>

        <% @all_tasks.each do |task| %>
            <div class = "taskcard">
                <h4> <%= task.subject %> - <%= task.task %> </h4>
                <h5> due in  <%= distance_of_time_in_words(Time.zone.now,task.due_date) %> </h5>
            </div>
        <% end %>


    </div>

    <div class = "col-md-6">

        <h5>Teacher:
            <%= @teacher_other.first_name %> <%= @teacher_other.last_name %>
        <h5>

        <div class = "teacher_tips1">
            <div type = 'teacher_tips'>

            <h3>Feedback tip</h3>

            <p> <%= @tip.body %> </p>

            </div>
        </div>
    </div>
</div>






<!-- The row with the grades -->
<div class = "row">


    <!-- English grades -->
    <div class = "col-md-6">
        <% unless @latest_two_english_grade.blank? %>
            <h2>Most recent English grades</h2>
            <% end %>

            <% @latest_two_english_grade.each do |grades| %>
              <div class="card">
                <h1 class="card-header"><%= grades.title %> </h1>
                <h2 class="card-subheader"><%=grades.subcategory%> </h2>
                <hr class="card-divider" />
                <li>Performance: <%=grades.performance_grade  %></li>
                <li>Feedback: "<%= grades.feedback  %>"</li>
                <li> Published <%= time_ago_in_words(grades.grade_date) %> ago</li>

            </div>
        <% end %>

        <div class = "viewall">
            <%= link_to('View all English Grades', english_grade_path(:id => current_user.id) )  %>
        </div>
    </div>


    <!-- Maths grades -->
    <div class = "col-md-6">
    <% unless @latest_two_maths_grade.blank? %>
        <h2>Most recent Maths grades</h2>
        <% end %>
        <% @latest_two_maths_grade.each do |grades| %>


          <div class="card">
            <h1 class="card-header"><%= grades.title %> </h1>
            <h2 class="card-subheader"><%=grades.subcategory%></h2>
            <hr class="card-divider" />
            <li>Performance: <%=grades.performance_grade  %></li>
            <li>Feedback: "<%= grades.feedback  %>"</li>
            <li> Published <%= time_ago_in_words(grades.grade_date) %> ago</li>

          </div>
    <% end %>
<div class = "viewall">
    <%= link_to('View all Maths Grades', maths_grade_path(:id => current_user.id) )  %>
</div>
    </div>
</div>

app/views/student/show.html.erb
<head>
<link href='https://fonts.googleapis.com/css?family=Open+Sans&subset=latin,latin-ext' rel='stylesheet' type='text/css'>


<style>
body {
   background: url(https://photos-6.dropbox.com/t/2/AABO-zyEY2tOjMWLE104A8VUTNP-OKx3304nOyxkkd4SUA/12/232060938/jpeg/32x32/1/_/1/2/2015-09-Life-of-Pix-free-stock-photos-road-desert-bus-fresonneveld.jpg/EMGkycQBGNe4AiAHKAc/1FCxtUYuYCMA_UVWkGTRrrdc-EXOXR8d4yf0iBn_sZg?dl=0&size=2048x1536&size_mode=3);

}



</style>
</head>




<% if user_signed_in? %>
<ul id="navbar">
    <li><%= link_to('Home', root_path)  %></li>
    <li><%= link_to('Settings', edit_user_registration_path)  %></li>
    <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
</ul>
<% else %>
<ul id="navbar">
    <li><%= link_to('Home', root_path)  %></li>
    <li><%= link_to('Login', new_user_session_path)  %></li>
</ul>
<% end %>

<div class = "row">
  <div class = "col-md-4">
    <h2> <%= @student.first_name %> <%= @student.last_name %> </h2>
  </div>
  <div class = "col-md-4"> </div>
  <div class = "col-md-4">
    <div class = "student_details">
      <h5> <%= @student.email %> </h5>
      <h5> Number of logins: <%= @student.sign_in_count %> </h5>
      <h5> Last logged in <%= distance_of_time_in_words(Time.zone.now, @student.last_sign_in_at.to_time) %> ago </h5>
    </div>
  </div>



</div>


<div class = "row">
<!-- English grades -->
<div class = "col-md-6">
<% unless @latest_two_english_grade.blank? %>
<h3>Most recent English grades</h3>
<% end %>

<% @latest_two_english_grade.each do |grades| %>

  <div class="card">
        <div class="card-actions animate">
      <% if Time.zone.now < grades.grade_date && current_user.type == 'Teacher' %> <%= link_to('Edit', edit_english_grade_path(grades)) %> |
      <td><%= link_to 'Delete', grades, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% elsif current_user.type == 'Teacher' %>
          Grade delivered
      <% end %>
    </div>
    <h1 class="card-header"><%= grades.title %> </h1>
    <h2 class="card-subheader"><%=grades.subcategory%> <%= grades.grade_date %> </h2>
    <hr class="card-divider" />
    <li>Performance: <%=grades.performance_grade  %></li>
    <li>Feedback: "<%= grades.feedback  %>"</li>
    <% if Time.zone.now < grades.grade_date %>
      <li> Goes live in <%= distance_of_time_in_words(Time.zone.now, grades.grade_date) %>  </li>
    <% else %>
      <li> Published <%= distance_of_time_in_words(Time.zone.now, grades.grade_date) %> ago  </li>
    <% end %>
    <% if @student.last_sign_in_at >= grades.grade_date %>
    <div class = "read"><li> read</li></div>
    <% else %>
    <div class = "unread"><li> unread </li></div>
<% end %>

</div>
<% end %>

<% unless @latest_two_english_grade.blank? %>
  <div class = "viewall1">
    <%= link_to('View all English Grades', english_grade_path(:id => @student.id) )  %> 
    <% end %>
     | <%= link_to('Create English Grade', new_english_grade_path(:student_id => @student.id, :teacher_id => current_user.id))  %>
  </div>
</div>
<!-- Maths grades -->
<div class = "col-md-6">

<% unless @latest_two_maths_grade.blank? %>
<h3>Most recent Maths grades</h3>
<% end %>
<% @latest_two_maths_grade.each do |grades| %>


  <div class="card">
        <div class="card-actions animate">
      <% if Time.zone.now < grades.grade_date && current_user.type == 'Teacher' %> <%= link_to('Edit', edit_english_grade_path(grades)) %> |
      <td><%= link_to 'Delete', grades, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% elsif current_user.type == 'Teacher' %>
      Grade delivered
      <% end %>
    </div>
    <h1 class="card-header"><%= grades.title %> </h1>
    <h2 class="card-subheader"><%=grades.subcategory%> <%= grades.grade_date %> </h2>
    <hr class="card-divider" />
    <li>Performance: <%=grades.performance_grade  %></li>
    <li>Feedback: "<%= grades.feedback  %>"</li>
    <% if Time.zone.now < grades.grade_date %>
      <li> Goes live in <%= distance_of_time_in_words(Time.zone.now, grades.grade_date) %>  </li>
    <% else %>
      <li> Published <%= distance_of_time_in_words(Time.zone.now, grades.grade_date) %> ago</li>
    <% end %>

    <% if @student.last_sign_in_at >= grades.grade_date %>
    <div class = "read"><li> read</li></div>
    <% else %>
    <div class = "unread"><li> unread </li></div>
<% end %>

  </div>
<% end %>

<% unless @latest_two_maths_grade.blank? %>
  <div class = "viewall1">
    <%= link_to('View all Maths Grades', maths_grade_path(:id => @student.id) )  %> 
    <% end %>
    |
    <%= link_to('Create Maths Grade', new_maths_grade_path(:student_id => @student.id, :teacher_id => current_user.id))  %>
  </div>


</div>
</div>

<br>
<div class = "back_button">
      <div class = "buttonscolour">
        <%= link_to "Back", root_path, :class => "btn btn-primary" %>
      </div>
</div>
<br>





<!-- Maths grades -->