config/routes.rb
Rails.application.routes.draw do

  resources :statistics
  resources :shortcut_texts
  resources :tips
  resources :tasks
  resources :generated_feedbacks
  resources :maths_grades
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
post 'signup' => 'devise/registrations#create', :as => :custom_user_registration

devise_scope :user do
  root to: "devise/sessions#new"
end

 resources :teacher

 resources :student
resources :english_grades


 resources :choose_subjects
 resources :choose_feedback_generator

 resources :edit_auto_gens
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/english_grade.rb
class EnglishGrade < ApplicationRecord
  belongs_to :teacher
  belongs_to :student
end

app/models/generated_feedback.rb
class GeneratedFeedback < ApplicationRecord
  belongs_to :teacher
end

app/models/maths_grade.rb
class MathsGrade < ApplicationRecord
  belongs_to :teacher
  belongs_to :student
end

app/models/shortcut_text.rb
class ShortcutText < ApplicationRecord
  belongs_to :teacher
end

app/models/statistic.rb
class Statistic < ApplicationRecord
end

app/models/student.rb
class Student < User
    has_many :grades
    has_many :maths_grades
    has_many :english_grades
    has_many :generated_feedback
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :teacher
end

app/models/teacher.rb
class Teacher < User
    has_many :grades
    has_many :maths_grades
    has_many :english_grades
    has_many :generated_feedback
    has_many :task
    has_many :shortcut_text
end

app/models/tip.rb
class Tip < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

def index
end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new :teacher_id => params[:teacher_id]
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)


      if @task.save
        redirect_to(teacher_index_path, :notice => "Task was successfully created.")
      else
        redirect_to(teacher_index_path, :notice => "Task was not successfully created.")
      end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
      if @task.update(task_params)
        redirect_to(teacher_index_path, :notice => "Task was successfully created.")
      else
        redirect_to(teacher_index_path, :notice => "Task was not successfully created.")
      end

  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    if @task.destroy
        redirect_to(teacher_index_path, :notice => "Task was successfully deleted.")
    else
        redirect_to(teacher_index_path, :notice => "Task was successfully deleted.")

    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:subject, :task, :teacher_id, :due_date, :description)
    end
end

app/controllers/teacher_controller.rb
class TeacherController < ApplicationController
before_filter :authenticate_user!
    def index
        @teacher = Teacher.find_by_id(current_user.id)
        @all_students = Student.where('teacher_email' => current_user.email)

        #feedback
        #@all_generated_feedback = GeneratedFeedback.where({teacher_id: current_user.id, subject: 'English'}).all


        #tasks
        @all_tasks = Task.where({teacher_id: current_user.id})

        #shortcut texts
        @all_shortcut_texts = ShortcutText.where({teacher_id: current_user.id})

        @students = User.all


    end
#User.where(teacher_email: current_user.email)
    def first_name
        @first_name = Teacher.first_name
    end



end

app/controllers/tips_controller.rb
class TipsController < ApplicationController
  before_action :set_tip, only: [:show, :edit, :update, :destroy]

  # GET /tips
  # GET /tips.json
  def index
    @tips = Tip.all
  end

  # GET /tips/1
  # GET /tips/1.json
  def show
  end

  # GET /tips/new
  def new
    @tip = Tip.new
  end

  # GET /tips/1/edit
  def edit
  end

  # POST /tips
  # POST /tips.json
  def create
    @tip = Tip.new(tip_params)

    respond_to do |format|
      if @tip.save
        format.html { redirect_to @tip, notice: 'Tip was successfully created.' }
        format.json { render :show, status: :created, location: @tip }
      else
        format.html { render :new }
        format.json { render json: @tip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tips/1
  # PATCH/PUT /tips/1.json
  def update
    respond_to do |format|
      if @tip.update(tip_params)
        format.html { redirect_to @tip, notice: 'Tip was successfully updated.' }
        format.json { render :show, status: :ok, location: @tip }
      else
        format.html { render :edit }
        format.json { render json: @tip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tips/1
  # DELETE /tips/1.json
  def destroy
    @tip.destroy
    respond_to do |format|
      format.html { redirect_to tips_url, notice: 'Tip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tip
      @tip = Tip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tip_params
      params.require(:tip).permit(:title, :body, :audience)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/maths_grades_helper.rb
module MathsGradesHelper
end

app/helpers/statistics_helper.rb
module StatisticsHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/teacher_helper.rb
module TeacherHelper


def students_by_logins
    bar_chart @all_students.group(:sign_in_count).count, height: '300px', width: '500px', library: {
      title: {text: 'How often parents have logged in', x: -20},
      yAxis: {
         allowDecimals: false,
         title: {
             text: 'number of parents'
         }
      },
      xAxis: {
         title: {
             text: 'number of logins'
         }
      }
    }
  end

end

app/helpers/tips_helper.rb
module TipsHelper
end

app/views/teacher/index.html.erb
<head>
<link href='https://fonts.googleapis.com/css?family=Open+Sans&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>
<meta name="turbolinks-cache-control" content="no-cache">

<style>
body {
   background: url(https://photos-6.dropbox.com/t/2/AABO-zyEY2tOjMWLE104A8VUTNP-OKx3304nOyxkkd4SUA/12/232060938/jpeg/32x32/1/_/1/2/2015-09-Life-of-Pix-free-stock-photos-road-desert-bus-fresonneveld.jpg/EMGkycQBGNe4AiAHKAc/1FCxtUYuYCMA_UVWkGTRrrdc-EXOXR8d4yf0iBn_sZg?dl=0&size=2048x1536&size_mode=3);


}

h2 {
  color:white;
}

.gen_shortcuts {
    width:500px;
    height:100px;
    background-color:white;
    z-index:0;
    opacity:0.7;
}


#tasktitle {
  margin: 15px;
}
#shortcuts{
  margin: 4px;
}

#parentgraph {
  right: -54px;
  position: relative;
}

#tasksbutton {
  margin: 15px;
}
</style>



<!-- <script src="http://code.highcharts.com/highcharts.js"></script> -->
</head>
<% content_for :title, "Home" %>

<% if user_signed_in? %>
<ul id="navbar">
    <li class="active"><%= link_to("#{current_user.first_name} #{current_user.last_name} (Teacher)" , root_path)  %></li>
    <li><%= link_to('Settings', edit_user_registration_path)  %></li>
    <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
</ul>
<% else %>
<ul id="navbar">
    <li><%= link_to('Home', root_path)  %></li>
    <li><%= link_to('Login', new_user_session_path)  %></li>
</ul>
<% end %>

<body>



<div class = "row">
  <!--The left hand side -->

<div class = "col-md-4">
 <div class = "row">

        <div class = "container1">
            <div class = "searchboxteacher">
                <div class="container" data-behaviour="search-on-list">
                    <input type="text" class="input-query" data-search-on-list="search" placeholder="Find student"/>

                    <div class="list-wrap">
                      <ul class="list" data-search-on-list="list">
                        <% @all_students.each do |student| %>
                          <li class="list-item" data-search-on-list="list-item">
                            <a href="../student/<%= student.id%>" class="list-item-link">
                                <%= student.first_name %> <span class="item-list-subtext"><%= student.last_name %></span>
                            </a>
                          </li>
                       <% end %>
                      </ul>
                    </div>
                </div>
            </div>

      </div>


<div class = "row" id = "parentgraph">
        <h2>Parental login statistics </h2>
      <%= students_by_logins %>
</div>



    </div>

<!-- Right Hand Side - Second row -->


</div>

  <!--Middle section - empty -->
<div class = "col-md-2">
</div>

<!-- Right hand side -->
<div class = "col-md-5">
       <!-- Right Hand Side - Second row -->

  <!-- top right -->
  <div class ="row">
    <div id = "tasksbutton">
     <h2>Tasks</h2>
            <div class = "buttonscolour">
              <%= link_to "New", new_task_path(:teacher_id => @teacher.id), :class => "btn btn-primary" %>
            </div>
    </div>
      <% @all_tasks.each do |task| %>
        <div class="card">
          <div class="card-actions animate">
            <%= link_to('Edit', edit_task_path(task)) %> |
               <td><%= link_to 'Delete', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </div>
          <h1 class="card-header"><%= task.due_date %> </h1>
          <h2 class="card-subheader"><%=task.subject%>  </h2>
          <hr class="card-divider" />
          <h3> <%= task.task %> </h3>
      </div>
    <% end %>
  </div>

    <div class = "row" id = "shortcuts">
      <h2>Shortcut text</h2>
      <div class = "buttonscolour">
        <%= link_to "View/Edit", edit_auto_gens_path, :class => "btn btn-primary" %>
      </div>
      <br>
      <h2>General shortcuts </h2>
      <div class = "buttonscolour">
          <%= link_to "New", new_shortcut_text_path(:teacher_id => @teacher.id), :class => "btn btn-primary" %>
      </div>
      <% @all_shortcut_texts.each do |shortcut| %>
      <div class = "gen_shortcuts"</div>
        <h3>
            <%= shortcut.body %> <br> <%= link_to('Edit', edit_shortcut_text_path(shortcut))  %> | <td><%= link_to 'Delete', shortcut, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </h3>
      </div>
      <% end %>

    </div>


</div>



  </div>











</div>

</div>
<!-- Right hand margin -->
<div class = "col-md-1">
</div>

</body>