config/routes.rb
Rails.application.routes.draw do

  resources :statistics
  resources :shortcut_texts
  resources :tips
  resources :tasks
  resources :generated_feedbacks
  resources :maths_grades
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
post 'signup' => 'devise/registrations#create', :as => :custom_user_registration

devise_scope :user do
  root to: "devise/sessions#new"
end

 resources :teacher

 resources :student
resources :english_grades


 resources :choose_subjects
 resources :choose_feedback_generator

 resources :edit_auto_gens
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/english_grade.rb
class EnglishGrade < ApplicationRecord
  belongs_to :teacher
  belongs_to :student
end

app/models/generated_feedback.rb
class GeneratedFeedback < ApplicationRecord
  belongs_to :teacher
end

app/models/maths_grade.rb
class MathsGrade < ApplicationRecord
  belongs_to :teacher
  belongs_to :student
end

app/models/shortcut_text.rb
class ShortcutText < ApplicationRecord
  belongs_to :teacher
end

app/models/statistic.rb
class Statistic < ApplicationRecord
end

app/models/student.rb
class Student < User
    has_many :grades
    has_many :maths_grades
    has_many :english_grades
    has_many :generated_feedback
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :teacher
end

app/models/teacher.rb
class Teacher < User
    has_many :grades
    has_many :maths_grades
    has_many :english_grades
    has_many :generated_feedback
    has_many :task
    has_many :shortcut_text
end

app/models/tip.rb
class Tip < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/generated_feedbacks_controller.rb
class GeneratedFeedbacksController < ApplicationController
  before_action :set_generated_feedback, only: [:show, :edit, :update, :destroy]

  # GET /generated_feedbacks
  # GET /generated_feedbacks.json
  def index
    @generated_feedbacks = GeneratedFeedback.all
  end

  # GET /generated_feedbacks/1
  # GET /generated_feedbacks/1.json
  def show
  end

  # GET /generated_feedbacks/new
  def new
    @generated_feedback = GeneratedFeedback.new :teacher_id => params[:teacher_id], :performance_grade => params[:performance_grade], :subject => params[:subject], :subcategory => params[:subcategory]
  end

  # GET /generated_feedbacks/1/edit
  def edit
  end

  # POST /generated_feedbacks
  # POST /generated_feedbacks.json
  def create
    @generated_feedback = GeneratedFeedback.new(generated_feedback_params)

      if @generated_feedback.save
      redirect_to(edit_auto_gens_path, :notice => "Generated feedback was successfully created.")
    else
      redirect_to(edit_auto_gens_path, :notice => "Generated feedback was not successfully created.")
    end
  end

  # PATCH/PUT /generated_feedbacks/1
  # PATCH/PUT /generated_feedbacks/1.json
  def update

    if @generated_feedback.update(generated_feedback_params)
      redirect_to(edit_auto_gens_path, :notice => "Generated feedback was successfully edited.")
    else
      redirect_to(edit_auto_gens_path, :notice => "Generated feedback was not successfully edited.")
    end
  end

  # DELETE /generated_feedbacks/1
  # DELETE /generated_feedbacks/1.json
  def destroy
    if @generated_feedback.destroy
      redirect_to(edit_auto_gens_path, :notice => "Generated feedback was successfully destroyed.")
    else
      redirect_to(edit_auto_gens_path, :notice => "Generated feedback was not successfully destroyed.")
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_generated_feedback
      @generated_feedback = GeneratedFeedback.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def generated_feedback_params
      params.require(:generated_feedback).permit(:performance_grade, :teacher_id, :subject, :auto_feedback, :subcategory)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

def index
end

end

app/controllers/tips_controller.rb
class TipsController < ApplicationController
  before_action :set_tip, only: [:show, :edit, :update, :destroy]

  # GET /tips
  # GET /tips.json
  def index
    @tips = Tip.all
  end

  # GET /tips/1
  # GET /tips/1.json
  def show
  end

  # GET /tips/new
  def new
    @tip = Tip.new
  end

  # GET /tips/1/edit
  def edit
  end

  # POST /tips
  # POST /tips.json
  def create
    @tip = Tip.new(tip_params)

    respond_to do |format|
      if @tip.save
        format.html { redirect_to @tip, notice: 'Tip was successfully created.' }
        format.json { render :show, status: :created, location: @tip }
      else
        format.html { render :new }
        format.json { render json: @tip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tips/1
  # PATCH/PUT /tips/1.json
  def update
    respond_to do |format|
      if @tip.update(tip_params)
        format.html { redirect_to @tip, notice: 'Tip was successfully updated.' }
        format.json { render :show, status: :ok, location: @tip }
      else
        format.html { render :edit }
        format.json { render json: @tip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tips/1
  # DELETE /tips/1.json
  def destroy
    @tip.destroy
    respond_to do |format|
      format.html { redirect_to tips_url, notice: 'Tip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tip
      @tip = Tip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tip_params
      params.require(:tip).permit(:title, :body, :audience)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/generated_feedbacks_helper.rb
module GeneratedFeedbacksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/maths_grades_helper.rb
module MathsGradesHelper
end

app/helpers/statistics_helper.rb
module StatisticsHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/teacher_helper.rb
module TeacherHelper


def students_by_logins
    bar_chart @all_students.group(:sign_in_count).count, height: '300px', width: '500px', library: {
      title: {text: 'How often parents have logged in', x: -20},
      yAxis: {
         allowDecimals: false,
         title: {
             text: 'number of parents'
         }
      },
      xAxis: {
         title: {
             text: 'number of logins'
         }
      }
    }
  end

end

app/helpers/tips_helper.rb
module TipsHelper
end

app/views/generated_feedbacks/_form.html.erb
<%= form_for(generated_feedback) do |f| %>
  <% if generated_feedback.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(generated_feedback.errors.count, "error") %> prohibited this generated_feedback from being saved:</h2>

      <ul>
      <% generated_feedback.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :performance_grade %>
  </div>


  <div class="field">
    <%= f.hidden_field :teacher_id %>
  </div>

  <div class="field">
    <%= f.hidden_field :subject %>
  </div>

  <div class="field">
    <%= f.text_area :auto_feedback %>
  </div>

  <div class="field">
    <%= f.hidden_field :subcategory %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/generated_feedbacks/edit.html.erb
<head>
<link href='https://fonts.googleapis.com/css?family=Open+Sans&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
</head>

<% if user_signed_in? %>
<ul id="navbar">
    <li><%= link_to('Home', root_path)  %></li>
    <li><%= link_to('Settings', edit_user_registration_path)  %></li>
    <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
</ul>
<% else %>
<ul id="navbar">
    <li><%= link_to('Home', root_path)  %></li>
    <li><%= link_to('Login', new_user_session_path)  %></li>
</ul>
<% end %>


<h1>Editing Generated Feedback</h1>

<%= render 'form', generated_feedback: @generated_feedback %>
      <div class = "buttonscolour">
        <%= link_to "Back", edit_auto_gens_path, :class => "btn btn-primary" %>
      </div>

app/views/generated_feedbacks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Generated Feedbacks</h1>

<table>
  <thead>
    <tr>
      <th>Performance grade</th>
      <th>Teacher</th>
      <th>Subject</th>
      <th>Auto feedback</th>
      <th>Subcategory</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @generated_feedbacks.each do |generated_feedback| %>
      <tr>
        <td><%= generated_feedback.performance_grade %></td>
        <td><%= generated_feedback.teacher %></td>
        <td><%= generated_feedback.subject %></td>
        <td><%= generated_feedback.auto_feedback %></td>
        <td><%= generated_feedback.subcategory %></td>
        <td><%= link_to 'Show', generated_feedback %></td>
        <td><%= link_to 'Edit', edit_generated_feedback_path(generated_feedback) %></td>
        <td><%= link_to 'Destroy', generated_feedback, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Generated Feedback', new_generated_feedback_path %>

app/views/generated_feedbacks/new.html.erb
<head>
<link href='https://fonts.googleapis.com/css?family=Open+Sans&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
</head>

<% if user_signed_in? %>
<ul id="navbar">
    <li><%= link_to('Home', root_path)  %></li>
    <li><%= link_to('Settings', edit_user_registration_path)  %></li>
    <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
</ul>
<% else %>
<ul id="navbar">
    <li><%= link_to('Home', root_path)  %></li>
    <li><%= link_to('Login', new_user_session_path)  %></li>
</ul>
<% end %>
<h1>New shortcut text</h1>

<%= render 'form', generated_feedback: @generated_feedback %>

      <div class = "buttonscolour">
        <%= link_to "Back", edit_auto_gens_path, :class => "btn btn-primary" %>
      </div>

app/views/generated_feedbacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Performance grade:</strong>
  <%= @generated_feedback.performance_grade %>
</p>

<p>
  <strong>Teacher:</strong>
  <%= @generated_feedback.teacher %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @generated_feedback.subject %>
</p>

<p>
  <strong>Auto feedback:</strong>
  <%= @generated_feedback.auto_feedback %>
</p>

<p>
  <strong>Subcategory:</strong>
  <%= @generated_feedback.subcategory %>
</p>

<%= link_to 'Edit', edit_generated_feedback_path(@generated_feedback) %> |
<%= link_to 'Back', generated_feedbacks_path %>